### PR TITLE
Apache Netbeans (incubating) 9.0-vc3

### PR DESCRIPTION
**Pull request by cbm64chris**
This PR uplifts the nbscala plugin to Apache Netbeans (incubating) 9.0-vc3. The maven artifacts are not available as yet so you have to build them manually from the Netbeans source ([instructions](https://dzone.com/articles/apache-netbeans-and-scala)).

nbscala

### CODE REVIEW

**Comment by cbm64chris** [comment]
@dcaoyuan can we get this merged in? If you are not planning on supporting this any longer, do you want to transfer the repo to me so I can move it forward?

**Comment by akochnev** [comment]
@cbm64chris  - there is no need to "transfer the repo", is there ? Just fork it and apply your fixes going forward.

**Comment by Dirk-c-Walter** [comment]
This repo is still first in the google results and pointed to from various netbeans sites... If it is going unmaintened please add a pointer to the new repo?

**Comment by cbm64chris** [comment]
Merged into nb9.x on my fork.

**Pull request closed without merging**
