### PR TITLE
Applied @pvgoran 's patch to remove unused implementation dependencies for #174

### PR DESCRIPTION
**Pull request by akochnev**
Applied patch, bumped dependency versions

### CODE REVIEW

**Comment by akochnev** [comment]
@dcaoyuan  - no interest in taking this fix ? It seems that it further reduces the need to re-publish a new version of the plugin on each netbeans release by reducing implementation dependencies.

**Comment by dcaoyuan** [comment]
@akochnev I'm not sure if this patch will cause nbscala cannot run under NetBeans' at runtime. I'll try to track the new NetBeans development under Apache, and if possible, patch, PR to NetBeans to resolve the friend dependencies of NetBeans' module

**Comment by barulheira** [comment]
I had to apply this patch to the plugin for Apache NetBeans IDE (incubator) and it's working.

**Comment by ColinWa** [comment]
@barulheira. Please kindly explained how you applied this patch on incubator. Thanks in advance.

**Comment by barulheira** [comment]
I can't remember anymore. It's been a long time since.

As far as I can remember, I got the plugin sources, applied the patch, and then I built the plugin according to build instructions. (Perhaps I remembered to update slightly the version number before.)

**Pull request closed without merging**
